export const ActionTypes = {

    SET_TOKEN:"SET_TOKEN",
    SET_AUTH_PENDING : "SET_AUTH_PENDING",
    SET_AUTH_SUCCESS : "SET_AUTH_SUCCESS",
    SET_AUTH_FAILURE : "SET_AUTH_FAILURE",

    SET_NEW_RELEASES : "SET_NEW_RELEASES",
    SET_NEW_RELEASES_PENDING : "SET_NEW_RELEASES_PENDING",
    SET_NEW_RELEASES_SUCCESS : "SET_NEW_RELEASES_SUCCESS",
    SET_NEW_RELEASES_FAILURE : "SET_NEW_RELEASES_FAILURE",

    SET_PLAYLISTS:"SET_PLAYLISTS",
    SET_PLAYLISTS_PENDING : "SET_PLAYLISTS_PENDING",
    SET_PLAYLISTS_SUCCESS : "SET_PLAYLISTS_SUCCESS",
    SET_PLAYLISTS_FAILURE : "SET_PLAYLISTS_FAILURE",

    SET_CATEGORIES:"SET_CATEGORIES",
    SET_CATEGORIES_PENDING : "SET_CATEGORIES_PENDING",
    SET_CATEGORIES_SUCCESS : "SET_CATEGORIES_SUCCESS",
    SET_CATEGORIES_FAILURE : "SET_CATEGORIES_FAILURE",
}