export const ActionTypes = {
    FETCH_NEW_RELEASES : "FETCH_NEW_RELEASES",
    FETCH_NEW_RELEASES_PENDING : "FETCH_NEW_RELEASES_PENDING",
    FETCH_NEW_RELEASES_SUCCESS : "FETCH_NEW_RELEASES_SUCCESS",
    FETCH_NEW_RELEASES_FAILURE : "FETCH_NEW_RELEASES_FAILURE",
    SET_NEW_RELEASES : "SET_NEW_RELEASES",
    SET_PLAYLISTS:"SET_PLAYLISTS",
    SET_CATEGORIES:"SET_CATEGORIES",
}